### ISSUE TITLE
Error retrieving v1.1.1 from JitPack

### ISSUE THREAD

**Issue by dugsmith** [bastienpaulfr/Treessence#23]
Hi @bastienpaulfr:

I just tried to use version 1.1.1 from JitPack with `implementation 'com.github.bastienpaulfr:Treessence:1.1.1'`, and it's failing for me. 

From [JitPack's site](https://jitpack.io/#bastienpaulfr/Treessence), it appears there's a build problem.

**Comment by dugsmith** [comment]
@bastienpaulfr : Do you know why the build is failing for this on JitPack?

**Comment by deRonbrown** [comment]
Jitpack doesn't seem compatible with 7.4.0 of the Android Gradle plugin. I've lowered the Gradle version and fixed the `FileLoggerTree` initializer in this PR: https://github.com/bastienpaulfr/Treessence/pull/25

Until this is merged in, you can grab my Jitpack changes using `com.github.deRonbrown:Treessence:1.1.3`.

**Comment by dugsmith** [comment]
Thank you, @deRonbrown! I appreciate you fixing that for us!

**Comment by MycroftWong** [comment]
Thank you, I just notice that loggingCoroutineScope isn't working before!
