### ISSUE TITLE
Device's Timezone information is getting lost

### ISSUE THREAD

**Issue by rvullriede** [bastienpaulfr/Treessence#3]
Hi,

thx for these usefuls trees. However, I've discovered that Treessence (specifically the helper method timestampToDate() in TimeUtils) set the JVM's default Timezone hardcoded to UTC.

This means after the first log statement has  been logged through Treessence the original timezone that was set by the user is lost!

**Comment by bastienpaulfr** [comment]
Hi thanks for your issue. It will be fixed in next version.

**Comment by RoryKelly** [comment]
Still exists in the latest version. happy to do a pr to fix

**Comment by bastienpaulfr** [comment]
Oups, my bad. 

I will be pleased to read your PR !

Tks

**Comment by bastienpaulfr** [comment]
Could you please test tz version and give me your feedback ?

Repo : https://dl.bintray.com/bastienpaulfr/maven-snapshot

repositories {
    maven { url 'https://dl.bintray.com/bastienpaulfr/maven-snapshot' }
    ...
}

dependencies {
    implementation 'fr.bipi.treessence:treessence:tz'
}

Tks

**Comment by bastienpaulfr** [comment]
I have just released 0.3.2 of lib !
