### ISSUE TITLE
Timezone Issues Again

### ISSUE THREAD

**Issue by Iamgiam** [bastienpaulfr/Treessence#5]
Hello. Just started using your library for file logging and am getting all times as US.
I use this in New Zealand. 
Can we get some form of timezone setting please. (ZoneId.of("NST"))

**Comment by bastienpaulfr** [comment]
Could you please test `tz` version and give me your feedback ?

Repo : https://dl.bintray.com/bastienpaulfr/maven-snapshot

```groovy
repositories {
    maven { url 'https://dl.bintray.com/bastienpaulfr/maven-snapshot' }
    ...
}

dependencies {
    implementation 'fr.bipi.treessence:treessence:tz'
}

```

Tks

**Comment by Iamgiam** [comment]
I have just added and ran the app the following was logged with the correct timestamp.
Thankyou 
02-22 07:28:09:361 I/JobSchedulerService(2) : Scheduled Job Started
02-22 07:28:09:375 E/JobMessageHandler(2) : ISJOBRUNNING == false
02-22 07:28:09:538 I/MyJobScheduler(2) : Job already scheduled
02-22 07:28:09:542 E/JobMessageHandler(2) : ISJOBRUNNING == false
02-22 07:29:03:722 I/PagerClassFragment$fapCountObserver(2) : FAPCount 495
02-22 07:29:03:731 I/PagerClassFragment$spkCountObserver(2) : SPKCount 200
02-22 07:29:04:477 I/MyJobScheduler(2) : JOB SCHEDULED! 3 Minutes
02-22 07:30:28:666 I/MyJobScheduler(2) : JOB SCHEDULED! 3 Minutes
02-22 07:30:29:409 I/PagerClassFragment$spkCountObserver(2) : SPKCount 200
02-22 07:30:29:421 I/PagerClassFragment$fapCountObserver(2) : FAPCount 495

**Comment by bastienpaulfr** [comment]
Thank you for testing. 

I will release the lib soon.

**Comment by bastienpaulfr** [comment]
0.3.2 version of lib has been released.
