### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by schauersbergern** [bastienpaulfr/Treessence#6]
Hello Bastien

Your lib is crashing:

at fr.bipi.tressence.file.FileLoggerTree$Builder.build(FileLoggerTree.java:242)

with 

java.nio.file.NoSuchFileException

I think you are using wrong paths, it should be the Apps file dir obtained from getFilesDir()

br, Nik

Please find the stacktrace attached
[stacktrace.txt](https://github.com/bastienpaulfr/Treessence/files/4656406/stacktrace.txt)

**Comment by akiller** [comment]
@schauersbergern 

I just came across this library myself and had the same problem.

The issue seems to be that you need to ensure your logs folder exists before setting up FileLoggerTree.

E.g.,:

`try {
	File logsDir = new File(getFilesDir(), "logs");
	if (!logsDir.exists())
		logsDir.mkdirs();

	Timber.plant(new FileLoggerTree.Builder()
			.withFileName("file%g.log")
			.withDir(logsDir)
			.withSizeLimit(200000)
			.withFileLimit(1)
			.withMinPriority(Log.VERBOSE)
			.appendToFile(true)
			.build());
} catch (IOException e) {
	e.printStackTrace();
}`

**Comment by schauersbergern** [comment]
@akiller, thanks for your suggestion!
I also added folder creation code, but I think this should be handled by the library. When I have a spare minute I will fix it and submit a pull request.

**Comment by DanteAndroid** [comment]
Hi, I still encoter this problem in 
    `implementation 'com.github.bastienpaulfr:Treessence:1.0.5'`
