### ISSUE TITLE
Extending FileLoggerTree with custom Formatter

### ISSUE THREAD

**Issue by l-lemesev** [bastienpaulfr/Treessence#8]
Hi there, nice lib.
My issue is that I couldn't find a nice way to supply a custom Formatter to the FileLoggerTree. I had to subclass it including builder and then set it in the constructor. Did I miss something or is it a good idea for improvement?

**Comment by bastienpaulfr** [comment]
`withFormatter()` method has been added in 1.0.0 version available on https://jitpack.io
